// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLfjinrSOef22A7OSmCKUYCtWB1J98Zzw',
    appId: '1:494198016954:web:e50ae55d725670014eab83',
    messagingSenderId: '494198016954',
    projectId: 'superpromo-2da3d',
    authDomain: 'superpromo-2da3d.firebaseapp.com',
    storageBucket: 'superpromo-2da3d.firebasestorage.app',
    measurementId: 'G-8JZ13HXN1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg0wTcwkFt2fC6WCZib8B3gLkBPhLO10k',
    appId: '1:494198016954:android:343f3d5a9ced2daf4eab83',
    messagingSenderId: '494198016954',
    projectId: 'superpromo-2da3d',
    storageBucket: 'superpromo-2da3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMZPH5YDXBTNnpVYBtn2BXVmzSmrc5QUU',
    appId: '1:494198016954:ios:dff87630d3a28c234eab83',
    messagingSenderId: '494198016954',
    projectId: 'superpromo-2da3d',
    storageBucket: 'superpromo-2da3d.firebasestorage.app',
    iosBundleId: 'br.caracol.superpromo',
  );

}